- iOS/second-hand/second-hand.xcodeproj/project.pbxproj
- iOS/second-hand/second-hand/UIColor+Extension.swift
- iOS/second-hand/second-hand/UIFont+Extension.swift
> [iOS] 컬러와 폰트 확장

- backend/src/main/java/com/team5/secondhand/global/config/WebConfig.java
> [#1] FEAT: cours 임시 설정

- iOS/second-hand/second-hand.xcodeproj/project.pbxproj
- iOS/second-hand/second-hand/Home/ButtonCustomView.swift
- iOS/second-hand/second-hand/Home/Controller/HomeViewController.swift
- iOS/second-hand/second-hand/Home/HomeLeftBarButton.swift
- iOS/second-hand/second-hand/Home/HomeRightBarButton.swift
- 타입 분리 
- 왼쪽 오른쪽 버튼 세팅 
- 왼쪽 버튼 dropdown은 추후 구현 예정
> 홈화면 bar button setting

- iOS/second-hand/second-hand/CategoriButton.swift
- iOS/second-hand/second-hand/Chatting/ChattingViewController.swift
- iOS/second-hand/second-hand/Home/ButtonCustomView.swift
- iOS/second-hand/second-hand/MyAccount/IdStackView.swift
- iOS/second-hand/second-hand/MyAccount/MyAccountViewController.swift
- iOS/second-hand/second-hand/SaleLog/Controller/SaleLogViewController.swift
- iOS/second-hand/second-hand/UIColor+Extension.swift
- iOS/second-hand/second-hand/UIFont+Extension.swift
- iOS/second-hand/second-hand/WishListViewController.swift
> [iOS] 색상/폰트/네비게이션하단라인

- front-end/src/App.tsx
- front-end/src/assets/Icon.tsx
- front-end/src/assets/svgs/index.ts
- front-end/src/assets/svgs/svg.d.ts
- svg 파일의 아이콘을 사용하기 위해 플러그인 설치 후 컴포넌트를 생성하였습니다.
> [#35] FEAT: Icon 컴포넌트 생성

- front-end/package.json
- front-end/src/components/common/Button/Button.tsx
- front-end/src/components/common/Button/index.ts
- front-end/src/styles/globalStyles.ts
- 타입, 사이즈 구분을 하였습니다.
- disabled 옵션을 적용하였습니다.
> [#42] 공통 버튼 컴포넌트 구현

- front-end/src/App.tsx
- front-end/src/pages/Layout.tsx
- front-end/src/pages/Login.tsx
- front-end/src/routes/AppRouter.tsx
- front-end/src/styles/globalStyles.ts
- 모바일 화면을 위한 레이아웃 컴포넌트를 생성하였습니다.
> [#53] mobile layout

- front-end/src/components/common/Chip/Chip.tsx
- front-end/src/components/common/Chip/index.ts
- 예약중, 카테고리 생성을 위한 Chip 컴포넌트를 생성하였습니다.
> [#37] FEAT: Chip 컴포넌트 생성

- front-end/src/components/common/PopupSheet/PopupSheet.tsx
- front-end/src/components/common/PopupSheet/index.ts
- front-end/src/constants/popupSheetMenu.ts
- front-end/src/pages/Layout.tsx
- front-end/tsconfig.json
- front-end/vite.config.ts
- slide Down, slide Up prop type으로 Popup의 형태를 다르게 설정하였습니다.
- 페이지별로 다른 메뉴의 텍스트를 constants 디렉토리에서 관리합니다.
- 추후 페이지에서 onClick 함수를 주입받아 사용해야합니다.
- 절대경로 `@constants` 를 생성하였습니다.
> [#43] FEAT: PopupSheet 컴포넌트 생성

- front-end/src/components/common/NavBar/NavBar.tsx
- front-end/src/components/common/NavBar/index.ts
- title 영역과 children 영역을 분리하였습니다.
- 페이지별로 컴포넌트를 props 를 전달받아 렌더링합니다.
> [#45] nav bar 컴포넌트 생성

- iOS/second-hand/second-hand.xcodeproj/project.pbxproj
- iOS/second-hand/second-hand/MyAccount/Controller/NotLoginMyAccountViewController.swift
- iOS/second-hand/second-hand/MyAccount/SubScene/Controller/GIthubWebViewController.swift
- iOS/second-hand/second-hand/MyAccount/SubScene/Controller/GithubWebViewController.swift
- iOS/second-hand/second-hand/MyAccount/SubScene/Controller/JoinViewController.swift
- iOS/second-hand/second-hand/MyAccount/View/IdStackView.swift
> [iOS] 깃허브로 로그인버튼 누르면 웹뷰 이동 +  회원가입시 아이디 로직 판단

- .github/workflows/publish.yml
> [#51] CHORE: gitaction 수정

- iOS/second-hand/second-hand.xcodeproj/project.pbxproj
- iOS/second-hand/second-hand/CategoryButton.swift
- iOS/second-hand/second-hand/CategoryScrollView.swift
- iOS/second-hand/second-hand/WishListViewController.swift
> [iOS] 위시리스트 코드리팩토링

- iOS/second-hand/second-hand/MyAccount/Controller/NotLoginMyAccountViewController.swift
- iOS/second-hand/second-hand/MyAccount/SubScene/Controller/JoinViewController.swift
> [iOS] 회원가입시 완료를 누르면 얼럿창 띄우기/ 로그인클릭시 바로 내계정 화면으로 넘어가기

- iOS/second-hand/second-hand/CategoryScrollView.swift
- iOS/second-hand/second-hand/Chatting/Controller/ChattingViewController.swift
- iOS/second-hand/second-hand/MyAccount/Controller/LoginMyAccountViewController.swift
- iOS/second-hand/second-hand/MyAccount/Controller/NotLoginMyAccountViewController.swift
- iOS/second-hand/second-hand/MyAccount/SubScene/Controller/JoinViewController.swift
> [iOS] 로그아웃 기능 구현 및 로그인되있을때 화면 세팅

- backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
> [#101] FEAT: 아이템 목록 보기 v0.2

- backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
> [#101] TEST: 임의로 like가 들어갈 수 있도록 수정

- backend/src/main/java/com/team5/secondhand/api/item/domain/Status.java
- backend/src/main/java/com/team5/secondhand/api/member/domain/Oauth.java
- backend/src/main/java/com/team5/secondhand/api/member/dto/request/MemberLogin.java
- backend/src/main/java/com/team5/secondhand/api/member/dto/response/MemberDetails.java
- item status 반환 형식 변경
- 1: 판매중, 2: 예약중, 3: 판매완료
- #101
> FEAT: DTO에 enum 표시 형식 변경

- backend/Dockerfile
- backend/build.gradle
- backend/docker-compose.yml
- backend/src/main/java/com/team5/secondhand/api/member/controller/MemberController.java
- backend/src/main/java/com/team5/secondhand/api/member/domain/Member.java
- backend/src/main/java/com/team5/secondhand/api/member/dto/request/MemberJoin.java
- backend/src/main/java/com/team5/secondhand/api/member/exception/ExistMemberIdException.java
- backend/src/main/java/com/team5/secondhand/api/member/exception/MemberDataCorruptedException.java
- backend/src/main/java/com/team5/secondhand/api/member/exception/MemberException.java
- backend/src/main/java/com/team5/secondhand/api/member/exception/MemberExceptionHandler.java
- backend/src/main/java/com/team5/secondhand/api/member/exception/NotValidMemberIdException.java
- backend/src/main/java/com/team5/secondhand/api/member/exception/UnauthorizedException.java
- backend/src/main/java/com/team5/secondhand/api/member/exception/UnauthorizedGithubMemberException.java
- backend/src/main/java/com/team5/secondhand/api/member/service/JoinService.java
- backend/src/main/java/com/team5/secondhand/api/member/service/MemberService.java
- backend/src/main/java/com/team5/secondhand/api/oauth/dto/UserProfile.java
- backend/src/main/java/com/team5/secondhand/api/oauth/service/OAuthService.java
- backend/src/main/java/com/team5/secondhand/global/dto/ErrorResponseWithBody.java
- backend/src/main/java/com/team5/secondhand/global/exception/GlobalExceptionHandler.java
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application.yml
- 회원가입 로직 수정
- https://second-hand-team5.notion.site/0178fc0b383d42f1b2854c40004e1a42?pvs=4
- #71 
- #81
> FEAT: 회원가입 로직 수정

- iOS/second-hand/second-hand/CategoryScrollView.swift
- iOS/second-hand/second-hand/MyAccount/Controller/LoginMyAccountViewController.swift
- iOS/second-hand/second-hand/MyAccount/Controller/NotLoginMyAccountViewController.swift
- iOS/second-hand/second-hand/MyAccount/SubScene/Controller/JoinViewController.swift
- iOS/second-hand/second-hand/MyAccount/View/IdStackView.swift
https://github.com/codesquad-members-2023/second-hand/pull/49
#118
> [iOS] 코드리뷰 반영

- backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
- backend/src/main/java/com/team5/secondhand/api/item/dto/response/ItemList.java
- backend/src/main/java/com/team5/secondhand/api/item/repository/ItemRepository.java
- backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
- backend/src/main/java/com/team5/secondhand/api/member/controller/MemberController.java
- backend/src/main/java/com/team5/secondhand/api/region/controller/RegionController.java
- `Item repository` 리스트 반환 Page -> Slice 로 반환
- #101
> FEAT: item page 반환시 이전/다음 페이지 여부와 함께 반환

- front-end/src/pages/WishList.tsx
- front-end/src/routes/router.tsx
- front-end/src/utils/getElapsedTime.ts
- path가 아직 Items이고, 데이터 나오는 대로 수정예정입니다.
> 관심목록 페이지 구현

- backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
- backend/src/main/java/com/team5/secondhand/api/item/domain/Item.java
- backend/src/main/java/com/team5/secondhand/api/item/domain/ItemContents.java
- backend/src/main/java/com/team5/secondhand/api/item/domain/ItemDetailImage.java
- backend/src/main/java/com/team5/secondhand/api/item/dto/request/ItemImage.java
- backend/src/main/java/com/team5/secondhand/api/item/dto/request/ItemPost.java
- backend/src/main/java/com/team5/secondhand/api/item/dto/response/ItemDetail.java
- backend/src/main/java/com/team5/secondhand/api/item/dto/response/Seller.java
- backend/src/main/java/com/team5/secondhand/api/item/exception/ItemExceptionHandler.java
- backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
- backend/src/main/java/com/team5/secondhand/api/member/controller/MemberController.java
- backend/src/main/java/com/team5/secondhand/api/member/dto/request/MemberProfileImageUpdate.java
- backend/src/main/java/com/team5/secondhand/api/region/controller/RegionController.java
- backend/src/main/java/com/team5/secondhand/global/aws/controller/ImageHostController.java
- backend/src/main/java/com/team5/secondhand/global/aws/dto/request/ItemImageUpload.java
- backend/src/main/java/com/team5/secondhand/global/aws/dto/response/ImageInfo.java
- backend/src/main/java/com/team5/secondhand/global/aws/service/ImageHostService.java
- backend/src/main/java/com/team5/secondhand/global/aws/service/usecase/ItemDetailImageUpload.java
- backend/src/main/java/com/team5/secondhand/global/aws/service/usecase/ItemThumbnailImageUpload.java
- backend/src/main/java/com/team5/secondhand/global/aws/service/usecase/ProfileUpload.java
- backend/src/main/resources/db/schema.sql
> 사진 업로드 및 아이템 상세조회 구현

- front-end/src/assets/Icon.tsx
- front-end/src/assets/svgs/index.ts
- front-end/src/assets/svgs/selected.svg
- front-end/src/assets/svgs/unselected.svg
- front-end/src/components/common/NavBar/NavBar.tsx
- front-end/src/components/common/PopupSheet/PopupSheet.tsx
- front-end/src/components/common/PopupSheet/constants.ts
- front-end/src/components/common/TabBar/SubTabBar.tsx
- front-end/src/components/login/OAuthCallback.tsx
- front-end/src/pages/Home.tsx
- front-end/src/pages/ItemDetail.tsx
- front-end/src/pages/Layout.tsx
> [#134] 아이템 상세 페이지 구현

- iOS/second-hand/second-hand.xcodeproj/project.pbxproj
- iOS/second-hand/second-hand/MyAccount/Controller/NotLoginMyAccountViewController.swift
- iOS/second-hand/second-hand/MyAccount/SubScene/GithubWeb/Controller/GithubWebViewController.swift
- iOS/second-hand/second-hand/NavigationUnderLineViewController.swift
- iOS/second-hand/second-hand/Network/Updatable.swift
- iOS/second-hand/second-hand/Network/UserInfoManager.swift
- 모델에 fetchedData 저장하는 흐름 수정 
- 로그인 관련 흐름 위주로 수정
> [iOS] #177 API연동 흐름 수정 

- backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
- backend/src/main/java/com/team5/secondhand/api/item/dto/response/CategoryList.java
- backend/src/main/java/com/team5/secondhand/api/item/repository/ItemRepository.java
- backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
- backend/src/main/java/com/team5/secondhand/api/member/service/MemberService.java
- backend/src/main/java/com/team5/secondhand/api/wishlist/controller/WishlistController.java
- backend/src/main/java/com/team5/secondhand/api/wishlist/domain/Wishlist.java
- backend/src/main/java/com/team5/secondhand/api/wishlist/dto/request/WishListItem.java
- backend/src/main/java/com/team5/secondhand/api/wishlist/dto/request/WishlistFilter.java
- backend/src/main/java/com/team5/secondhand/api/wishlist/dto/request/WishlistItem.java
- backend/src/main/java/com/team5/secondhand/api/wishlist/dto/response/CategoryList.java
- backend/src/main/java/com/team5/secondhand/api/wishlist/dto/response/WishItem.java
- backend/src/main/java/com/team5/secondhand/api/wishlist/dto/response/WishItemList.java
- backend/src/main/java/com/team5/secondhand/api/wishlist/exception/ExistWishlistException.java
- backend/src/main/java/com/team5/secondhand/api/wishlist/exception/WishlistExceptionHandler.java
- backend/src/main/java/com/team5/secondhand/api/wishlist/repository/WishlistRepository.java
- backend/src/main/java/com/team5/secondhand/api/wishlist/service/WishlistService.java
> 관심목록 API 완성

- front-end/src/components/login/UserProfile.tsx
> add profile size

- front-end/src/components/common/SegmentedControl/SegmentedControl.tsx
- front-end/src/components/common/SegmentedControl/index.ts
- front-end/src/pages/SalesHistory.tsx
> [#63] FEAT: SegmentedControl 컴포넌트 구현

- backend/docker-compose.yml
- backend/src/main/java/com/team5/secondhand/global/auth/interceptor/AuthorityInterceptor.java
- backend/src/main/java/com/team5/secondhand/global/config/WebConfig.java
- backend/src/main/resources/application-local.yml
> [#213] FIX: 인터셉터 수정

- iOS/second-hand/second-hand.xcodeproj/project.pbxproj
- iOS/second-hand/second-hand/Home/Controller/HomeViewController.swift
- iOS/second-hand/second-hand/Home/Model/SellingItem.swift
- iOS/second-hand/second-hand/Home/View/HomeProductCollectionViewCell.swift
- iOS/second-hand/second-hand/Info.plist
- iOS/second-hand/second-hand/UIExtensions/Int,String+Extension.swift
Cell UI API연동 & 리팩토링
UI API연동
constraint재설정
price 표기법 수정
status에 따른 view 표현 분기
타임스탬프 -> n분전 / n시간전 / n일전 으로 변환 후 View에 반영
> [iOS] CellUI API연동 

- backend/src/main/java/com/team5/secondhand/global/config/WebConfig.java
- BE cors 설정 수정
- yml 암호화
- #224
> FEAT: BE CORS 설정 수정

- front-end/package.json
- front-end/src/api.ts
- front-end/src/components/chat/ChatRoom/ChatRoom.tsx
- front-end/src/components/chat/ChatRoom/index.ts
- front-end/src/components/chat/ChatRoomList/ChatListItem.tsx
- front-end/src/components/chat/ChatRoomList/ChatRoomList.tsx
- front-end/src/components/common/ImgBox/ImgBox.tsx
- front-end/src/components/common/TabBar/ChatTabBar.tsx
- front-end/src/components/common/Textarea/Textarea.tsx
- front-end/src/pages/ChatPage.tsx
- front-end/src/pages/Home.tsx
> [#230] chat room UI 및 WS 통신 로직

- backend/src/main/java/com/team5/secondhand/api/chatroom/controller/ChatRoomController.java
- backend/src/main/java/com/team5/secondhand/api/chatroom/domian/ChatRoom.java
- backend/src/main/java/com/team5/secondhand/api/chatroom/dto/response/ChatroomDetails.java
- backend/src/main/java/com/team5/secondhand/api/chatroom/repository/ChatRoomRepository.java
- backend/src/main/java/com/team5/secondhand/api/chatroom/service/ChatRoomFacade.java
- backend/src/main/java/com/team5/secondhand/api/chatroom/service/ChatRoomService.java
- backend/src/test/java/com/team5/secondhand/api/chatroom/domian/ChatRoomTest.java
- 파라미터 시그니처 변경
- domain 시그니처 변경
- domain 멤버 시그니처  변경
- #260
> [#260] FIX: chat info debugging

- backend/src/main/java/com/team5/secondhand/api/wishlist/repository/WishlistRepository.java
> [#273] FIX: 쿼리 타입 오류 수정

- iOS/second-hand/second-hand/MyAccount/Controller/NotLoginMyAccountViewController.swift
- iOS/second-hand/second-hand/MyAccount/SubScene/Join/Controller/JoinViewController.swift
- iOS/second-hand/second-hand/Network/JSONCreater.swift
- iOS/second-hand/second-hand/Network/NetworkManager.swift
- iOS/second-hand/second-hand/Network/UserInfoManager.swift
- 로그인 이후 GET 요청에 로그인 토큰 삽입하는 기능 구현
> I os/271 refactor login flow

- backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
- backend/src/main/java/com/team5/secondhand/api/item/repository/ItemSliceRepositoryImpl.java
- backend/src/main/java/com/team5/secondhand/api/region/service/RegionService.java
- backend/src/main/java/com/team5/secondhand/global/config/WebConfig.java
- backend/src/main/resources/db/schema.sql
> FIX: chatroom API 구현에 대한 debugging

- backend/src/main/java/com/team5/secondhand/api/chatroom/controller/ChatroomController.java
- backend/src/main/java/com/team5/secondhand/api/chatroom/dto/request/ChatItem.java
- backend/src/main/java/com/team5/secondhand/api/chatroom/dto/response/ChatroomList.java
- backend/src/main/java/com/team5/secondhand/api/chatroom/exception/BuyerException.java
- backend/src/main/java/com/team5/secondhand/api/chatroom/exception/ChatRoomExceptionHandler.java
- backend/src/main/java/com/team5/secondhand/api/chatroom/repository/ChatroomRepository.java
- backend/src/main/java/com/team5/secondhand/api/chatroom/service/ChatroomFacade.java
- backend/src/main/java/com/team5/secondhand/api/chatroom/service/ChatroomService.java
- backend/src/main/java/com/team5/secondhand/api/item/domain/Item.java
- 채팅방 리스트 조회 시 페이징 처리
- 나와의 채팅 금지 예외처리 
- 멤버 및 아이템 존재여부 예외처리
> 채팅방 생성 및 리스트 조회 시 버그 수정

- backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
- backend/src/main/java/com/team5/secondhand/api/item/dto/request/MyItemFilteredSlice.java
- backend/src/main/java/com/team5/secondhand/api/item/dto/response/MyItemList.java
- backend/src/main/java/com/team5/secondhand/api/item/dto/response/MyItemSummary.java
- backend/src/main/java/com/team5/secondhand/api/item/repository/ItemRepository.java
- backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
> FEAT: 판매내역 API 수정

- backend/src/main/java/com/team5/secondhand/chat/bubble/domain/ChatBubble.java
- backend/src/main/java/com/team5/secondhand/chat/bubble/dto/response/BubbleSummary.java
- backend/src/main/java/com/team5/secondhand/chat/bubble/service/ChatLogService.java
- backend/src/main/java/com/team5/secondhand/chat/bubble/service/RedisMessagePublisher.java
- backend/src/main/java/com/team5/secondhand/global/config/RedisConfig.java
- backend/src/main/resources/application.yml
> FEAT: 채팅 DB 저장 구조 변경

- backend/src/main/java/com/team5/secondhand/chat/bubble/dto/response/BubbleSummary.java
> [#308] REFACTOR: DTO 필드명 변경

- backend/src/main/java/com/team5/secondhand/api/item/dto/request/ItemImage.java
- backend/src/main/java/com/team5/secondhand/api/member/service/MemberService.java
- backend/src/main/java/com/team5/secondhand/api/region/service/RegionService.java
- backend/src/main/java/com/team5/secondhand/global/jwt/config/AuthenticationFilter.java
> Refactor: 사용하지 않는 코드 삭제

- front-end/src/components/common/Alert/Alert.tsx
- front-end/src/components/common/Alert/constants.ts
- front-end/src/components/common/Alert/index.ts
- front-end/src/components/common/Alert/useAlert.tsx
- front-end/src/components/layout/PortalLayout.tsx
- front-end/src/pages/ItemDetail.tsx
> [#298] FEAT: Alert UI 컴포넌트 생성

- front-end/.env.production
- front-end/src/components/login/OAuthCallback.tsx
- ouath 인증후 Redirect url 진입을 위한 env 파일을 추가하였습니다.
- 기존 `.env` 파일에 `ENV_MODE` 변수 를 추가합니다.
```
VITE_ENV_MODE = PROD
```
> [#331] CHORE: ENV변수 설정

- front-end/src/components/common/Alert/Alert.tsx
- front-end/src/components/login/Join.tsx
- front-end/src/components/new/itemEditor/ItemEditor.tsx
- front-end/src/components/region/RegionSelector.tsx
- front-end/src/components/region/SettingRegionSelector.tsx
- front-end/src/pages/Home.tsx
- front-end/src/pages/Login.tsx
- 홈 에서 새 상품등록 시
- 로그인 페이지에서 로그아웃 시
- 내동네설정, 회원가입페이지에서 지역 삭제 시
> [#324] add alert

- front-end/src/components/common/TabBar/ChatTabBar.tsx
- front-end/src/hooks/useEnterKeyPress.tsx
- front-end/src/pages/Login.tsx
> [#340] FEAT: 엔터 키를 누를 때 특정 함수를 실행하는 커스텀 훅 작성

- front-end/src/components/common/Alert/Alert.tsx
- front-end/src/components/common/Item/Item.tsx
- front-end/src/components/common/PopupSheet/PopupSheet.tsx
- front-end/src/components/common/PopupSheet/constants.ts
- front-end/src/components/home/ItemList/ItemList.tsx
- front-end/src/components/home/category/category.tsx
- front-end/src/components/layout/MobileLayout.tsx
- front-end/src/components/layout/PortalLayout.tsx
- front-end/src/components/login/Join.tsx
- front-end/src/components/login/LoginButtons.tsx
- front-end/src/components/login/OAuthCallback.tsx
- front-end/src/components/new/CategoryList.tsx
- front-end/src/components/new/New.tsx
- front-end/src/components/new/itemEditor/ItemEditor.tsx
- front-end/src/components/new/itemEditor/TitleEditor.tsx
- front-end/src/components/region/SearchRegions.tsx
- front-end/src/components/region/SettingRegionSelector.tsx
- front-end/src/pages/Home.tsx
- front-end/src/pages/ItemDetail.tsx
- front-end/src/pages/Login.tsx
- front-end/src/pages/SalesHistory.tsx
- front-end/src/pages/WishList.tsx
- front-end/src/utils/formatText.ts
- front-end/src/utils/getElapsedTime.ts
- front-end/src/utils/sessionStorage.ts
- 관심목록에서 상품이 사라졌을 때 active한 카테고리를 "전체"로 수정
- 로그인 페이지 컨벤션에 맞는 prefix와 불필요한 useEffect 수정
- 판매목록에서 더보기 버튼을 통해 상품 수정, 상태변경 할 수 있게 로직 수정
- 포탈 컴포넌트에 createPortal을 선언하여 포탈을 사용할 때 마다 createPortal 선언을 하지 않도록 로직을 수정
> [#346] TODO 수정

- backend/src/main/java/com/team5/secondhand/api/chatroom/controller/ChatroomController.java
- backend/src/main/java/com/team5/secondhand/api/chatroom/service/ChatroomFacade.java
- backend/src/main/java/com/team5/secondhand/api/member/dto/response/MemberDetails.java
- backend/src/main/java/com/team5/secondhand/chat/chatroom/service/ChatroomCacheService.java
- 채팅 로그가 없는 경우, 채팅방 조회 null point 에러를 수정합니다.
> HOT FIX : 채팅방 목록 조회 에러 수정

- backend/src/main/java/com/team5/secondhand/api/chatroom/controller/ChatroomController.java
- backend/src/main/java/com/team5/secondhand/chat/notification/service/NotificationService.java
> [#390] HOTFIX: 중복 응답 헤더 제거

- backend/src/main/java/com/team5/secondhand/api/chatroom/domian/Chatroom.java
> HOT FIX: 기본키 생성 로직 추가

- backend/src/main/java/com/team5/secondhand/api/chatroom/dto/response/ChatroomList.java
- backend/src/main/java/com/team5/secondhand/api/chatroom/dto/response/ChatroomSummary.java
- backend/src/main/java/com/team5/secondhand/api/chatroom/service/ChatroomFacade.java
- backend/src/main/java/com/team5/secondhand/chat/bubble/controller/ChatController.java
- backend/src/main/java/com/team5/secondhand/chat/bubble/service/ChatBubbleService.java
> FEAT: 채팅방 정렬 기능 추가

- backend/src/main/java/com/team5/secondhand/api/item/service/ItemPostService.java
- backend/src/main/java/com/team5/secondhand/api/item/service/ItemReadService.java
> HOTFIX: 긴급 오류 수정

- backend/src/main/java/com/team5/secondhand/chat/bubble/dto/response/BubbleSummary.java
- backend/src/main/java/com/team5/secondhand/chat/bubble/service/ChatBubbleService.java
- 채팅 로그 반환시 `senderId` 키를 `sender`로 변경
> [#424] REFACTOR: View 반환 필드 시그니처 변경

- iOS/second-hand/second-hand/Chatting/subScene/PrivateChatroom/Controller/PrivateChatroomViewController.swift
- iOS/second-hand/second-hand/Network/CodableTemplate.swift
- iOS/second-hand/second-hand/Network/Server.swift
- iOS/second-hand/second-hand/Network/UserInfoManager.swift
- 변경된 API 적용 
- 채팅방 나가기 기능 구현 
- 일관성을 고려하여 변경된  api 키 값을 반영하였습니다. 
- senderId -> sender
- 채팅방 나가기 기능을 구현하였습니다.
> iOS #432 - 채팅방 개선 및 추가기능 구현 

- iOS/second-hand/second-hand.xcodeproj/project.pbxproj
- iOS/second-hand/second-hand/Home/subScene/RegisterNewProduct/Controller/RegisterNewProductViewController.swift
- iOS/second-hand/second-hand/MyAccount/Controller/LoginMyAccountViewController.swift
- iOS/second-hand/second-hand/Network/CodableTemplate.swift
- iOS/second-hand/second-hand/Network/MultipartTypeCreater.swift
- iOS/second-hand/second-hand/Network/NetworkManager.swift
- iOS/second-hand/second-hand/Network/Server.swift
- iOS/second-hand/second-hand/SaleLog/Controller/SaleLogViewController.swift
- 멀티파트 타입 관련 메소드 구현 및 개선 
- 프로필 사진 변경 기능 구현 
- PATCH 요청 메소드 개선
> iOS 437 - 프로필사진 변경 
